[".iterm2_shell_integration.zsh"]
    type = "file"
    url = "https://iterm2.com/shell_integration/zsh"
    refreshPeriod = "168h"

[".pyenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv.git"
    refreshPeriod = "168h"

[".pyenv/plugins/pyenv-update"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv-update.git"
    refreshPeriod = "168h"

[".pyenv/plugins/pyenv-doctor"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv-doctor.git"
    refreshPeriod = "168h"
